[server]
maxUploadSize = 1000
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
developmentMode = false

# Streamlit Cloud specific settings
[logger]
level = "info"

# Memory and performance settings
[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = false
